//-----------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//   Changes to this file may cause incorrect behavior and will be lost if
//   the code is regenerated.
//
//   For more information, see: http://go.microsoft.com/fwlink/?LinkID=623246
// </auto-generated>
//-----------------------------------------------------------------------------
#pragma once

namespace com { namespace lg { namespace Control { namespace TV {

public interface class ITVService
{
public:
    // Implement this function to handle calls to the DownChannel method.
    Windows::Foundation::IAsyncOperation<TVDownChannelResult^>^ DownChannelAsync(_In_ Windows::Devices::AllJoyn::AllJoynMessageInfo^ info );

    // Implement this function to handle calls to the GetChannelList method.
    Windows::Foundation::IAsyncOperation<TVGetChannelListResult^>^ GetChannelListAsync(_In_ Windows::Devices::AllJoyn::AllJoynMessageInfo^ info , _In_ uint16 interfaceMemberStartingRecord, _In_ uint16 interfaceMemberNumRecords);

    // Implement this function to handle calls to the KeyInput method.
    Windows::Foundation::IAsyncOperation<TVKeyInputResult^>^ KeyInputAsync(_In_ Windows::Devices::AllJoyn::AllJoynMessageInfo^ info , _In_ uint16 interfaceMemberVirtualKeyVal);

    // Implement this function to handle calls to the UpChannel method.
    Windows::Foundation::IAsyncOperation<TVUpChannelResult^>^ UpChannelAsync(_In_ Windows::Devices::AllJoyn::AllJoynMessageInfo^ info );

    // Implement this function to handle requests for the value of the ChannelID property.
    //
    // Currently, info will always be null, because no information is available about the requestor.
    Windows::Foundation::IAsyncOperation<TVGetChannelIDResult^>^ GetChannelIDAsync(Windows::Devices::AllJoyn::AllJoynMessageInfo^ info);

    // Implement this function to handle requests to set the ChannelID property.
    //
    // Currently, info will always be null, because no information is available about the requestor.
    Windows::Foundation::IAsyncOperation<TVSetChannelIDResult^>^ SetChannelIDAsync(Windows::Devices::AllJoyn::AllJoynMessageInfo^ info, Platform::String^ value);

    // Implement this function to handle requests for the value of the InputSource property.
    //
    // Currently, info will always be null, because no information is available about the requestor.
    Windows::Foundation::IAsyncOperation<TVGetInputSourceResult^>^ GetInputSourceAsync(Windows::Devices::AllJoyn::AllJoynMessageInfo^ info);

    // Implement this function to handle requests to set the InputSource property.
    //
    // Currently, info will always be null, because no information is available about the requestor.
    Windows::Foundation::IAsyncOperation<TVSetInputSourceResult^>^ SetInputSourceAsync(Windows::Devices::AllJoyn::AllJoynMessageInfo^ info, uint16 value);

    // Implement this function to handle requests for the value of the SupportedInputSources property.
    //
    // Currently, info will always be null, because no information is available about the requestor.
    Windows::Foundation::IAsyncOperation<TVGetSupportedInputSourcesResult^>^ GetSupportedInputSourcesAsync(Windows::Devices::AllJoyn::AllJoynMessageInfo^ info);

    // Implement this function to handle requests for the value of the Version property.
    //
    // Currently, info will always be null, because no information is available about the requestor.
    Windows::Foundation::IAsyncOperation<TVGetVersionResult^>^ GetVersionAsync(Windows::Devices::AllJoyn::AllJoynMessageInfo^ info);

};

} } } } 
