//-----------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//   Changes to this file may cause incorrect behavior and will be lost if
//   the code is regenerated.
//
//   For more information, see: http://go.microsoft.com/fwlink/?LinkID=623246
// </auto-generated>
//-----------------------------------------------------------------------------
#pragma once

using namespace concurrency;

namespace com { namespace lg { namespace Control { namespace TV {

ref class TVConsumer;

public ref class TVDownChannelResult sealed
{
public:
    property int32 Status
    {
        int32 get() { return m_status; }
    internal:
        void set(_In_ int32 value) { m_status = value; }
    }

    
    static TVDownChannelResult^ CreateSuccessResult()
    {
        auto result = ref new TVDownChannelResult();
        result->Status = Windows::Devices::AllJoyn::AllJoynStatus::Ok;
        result->m_creationContext = Concurrency::task_continuation_context::use_current();
        return result;
    }
    
    static TVDownChannelResult^ CreateFailureResult(_In_ int32 status)
    {
        auto result = ref new TVDownChannelResult();
        result->Status = status;
        return result;
    }
internal:
    Concurrency::task_continuation_context m_creationContext = Concurrency::task_continuation_context::use_default();

private:
    int32 m_status;
};

public ref class TVGetChannelListResult sealed
{
public:
    property int32 Status
    {
        int32 get() { return m_status; }
    internal:
        void set(_In_ int32 value) { m_status = value; }
    }

    property Windows::Foundation::Collections::IVector<TVListOfChannelsItem^>^ ListOfChannels
    {
        Windows::Foundation::Collections::IVector<TVListOfChannelsItem^>^ get() { return m_interfaceMemberListOfChannels; }
    internal:
        void set(_In_ Windows::Foundation::Collections::IVector<TVListOfChannelsItem^>^ value) { m_interfaceMemberListOfChannels = value; }
    }
    
    static TVGetChannelListResult^ CreateSuccessResult(_In_ Windows::Foundation::Collections::IVector<TVListOfChannelsItem^>^ interfaceMemberListOfChannels)
    {
        auto result = ref new TVGetChannelListResult();
        result->Status = Windows::Devices::AllJoyn::AllJoynStatus::Ok;
        result->ListOfChannels = interfaceMemberListOfChannels;
        result->m_creationContext = Concurrency::task_continuation_context::use_current();
        return result;
    }
    
    static TVGetChannelListResult^ CreateFailureResult(_In_ int32 status)
    {
        auto result = ref new TVGetChannelListResult();
        result->Status = status;
        return result;
    }
internal:
    Concurrency::task_continuation_context m_creationContext = Concurrency::task_continuation_context::use_default();

private:
    int32 m_status;
    Windows::Foundation::Collections::IVector<TVListOfChannelsItem^>^ m_interfaceMemberListOfChannels;
};

public ref class TVKeyInputResult sealed
{
public:
    property int32 Status
    {
        int32 get() { return m_status; }
    internal:
        void set(_In_ int32 value) { m_status = value; }
    }

    
    static TVKeyInputResult^ CreateSuccessResult()
    {
        auto result = ref new TVKeyInputResult();
        result->Status = Windows::Devices::AllJoyn::AllJoynStatus::Ok;
        result->m_creationContext = Concurrency::task_continuation_context::use_current();
        return result;
    }
    
    static TVKeyInputResult^ CreateFailureResult(_In_ int32 status)
    {
        auto result = ref new TVKeyInputResult();
        result->Status = status;
        return result;
    }
internal:
    Concurrency::task_continuation_context m_creationContext = Concurrency::task_continuation_context::use_default();

private:
    int32 m_status;
};

public ref class TVUpChannelResult sealed
{
public:
    property int32 Status
    {
        int32 get() { return m_status; }
    internal:
        void set(_In_ int32 value) { m_status = value; }
    }

    
    static TVUpChannelResult^ CreateSuccessResult()
    {
        auto result = ref new TVUpChannelResult();
        result->Status = Windows::Devices::AllJoyn::AllJoynStatus::Ok;
        result->m_creationContext = Concurrency::task_continuation_context::use_current();
        return result;
    }
    
    static TVUpChannelResult^ CreateFailureResult(_In_ int32 status)
    {
        auto result = ref new TVUpChannelResult();
        result->Status = status;
        return result;
    }
internal:
    Concurrency::task_continuation_context m_creationContext = Concurrency::task_continuation_context::use_default();

private:
    int32 m_status;
};

public ref class TVJoinSessionResult sealed
{
public:
    property int32 Status
    {
        int32 get() { return m_status; }
    internal:
        void set(_In_ int32 value) { m_status = value; }
    }

    property TVConsumer^ Consumer
    {
        TVConsumer^ get() { return m_consumer; }
    internal:
        void set(_In_ TVConsumer^ value) { m_consumer = value; }
    };

private:
    int32 m_status;
    TVConsumer^ m_consumer;
};

public ref class TVGetChannelIDResult sealed
{
public:
    property int32 Status
    {
        int32 get() { return m_status; }
    internal:
        void set(_In_ int32 value) { m_status = value; }
    }

    property Platform::String^ ChannelID
    {
        Platform::String^ get() { return m_value; }
    internal:
        void set(_In_ Platform::String^ value) { m_value = value; }
    }

    static TVGetChannelIDResult^ CreateSuccessResult(_In_ Platform::String^ value)
    {
        auto result = ref new TVGetChannelIDResult();
        result->Status = Windows::Devices::AllJoyn::AllJoynStatus::Ok;
        result->ChannelID = value;
        result->m_creationContext = Concurrency::task_continuation_context::use_current();
        return result;
    }

    static TVGetChannelIDResult^ CreateFailureResult(_In_ int32 status)
    {
        auto result = ref new TVGetChannelIDResult();
        result->Status = status;
        return result;
    }
internal:
    Concurrency::task_continuation_context m_creationContext = Concurrency::task_continuation_context::use_default();

private:
    int32 m_status;
    Platform::String^ m_value;
};

public ref class TVSetChannelIDResult sealed
{
public:
    property int32 Status
    {
        int32 get() { return m_status; }
    internal:
        void set(_In_ int32 value) { m_status = value; }
    }

    static TVSetChannelIDResult^ CreateSuccessResult()
    {
        auto result = ref new TVSetChannelIDResult();
        result->Status = Windows::Devices::AllJoyn::AllJoynStatus::Ok;
        result->m_creationContext = Concurrency::task_continuation_context::use_current();
        return result;
    }

    static TVSetChannelIDResult^ CreateFailureResult(_In_ int32 status)
    {
        auto result = ref new TVSetChannelIDResult();
        result->Status = status;
        return result;
    }
internal:
    Concurrency::task_continuation_context m_creationContext = Concurrency::task_continuation_context::use_default();

private:
    int32 m_status;
};

public ref class TVGetInputSourceResult sealed
{
public:
    property int32 Status
    {
        int32 get() { return m_status; }
    internal:
        void set(_In_ int32 value) { m_status = value; }
    }

    property uint16 InputSource
    {
        uint16 get() { return m_value; }
    internal:
        void set(_In_ uint16 value) { m_value = value; }
    }

    static TVGetInputSourceResult^ CreateSuccessResult(_In_ uint16 value)
    {
        auto result = ref new TVGetInputSourceResult();
        result->Status = Windows::Devices::AllJoyn::AllJoynStatus::Ok;
        result->InputSource = value;
        result->m_creationContext = Concurrency::task_continuation_context::use_current();
        return result;
    }

    static TVGetInputSourceResult^ CreateFailureResult(_In_ int32 status)
    {
        auto result = ref new TVGetInputSourceResult();
        result->Status = status;
        return result;
    }
internal:
    Concurrency::task_continuation_context m_creationContext = Concurrency::task_continuation_context::use_default();

private:
    int32 m_status;
    uint16 m_value;
};

public ref class TVSetInputSourceResult sealed
{
public:
    property int32 Status
    {
        int32 get() { return m_status; }
    internal:
        void set(_In_ int32 value) { m_status = value; }
    }

    static TVSetInputSourceResult^ CreateSuccessResult()
    {
        auto result = ref new TVSetInputSourceResult();
        result->Status = Windows::Devices::AllJoyn::AllJoynStatus::Ok;
        result->m_creationContext = Concurrency::task_continuation_context::use_current();
        return result;
    }

    static TVSetInputSourceResult^ CreateFailureResult(_In_ int32 status)
    {
        auto result = ref new TVSetInputSourceResult();
        result->Status = status;
        return result;
    }
internal:
    Concurrency::task_continuation_context m_creationContext = Concurrency::task_continuation_context::use_default();

private:
    int32 m_status;
};

public ref class TVGetSupportedInputSourcesResult sealed
{
public:
    property int32 Status
    {
        int32 get() { return m_status; }
    internal:
        void set(_In_ int32 value) { m_status = value; }
    }

    property Windows::Foundation::Collections::IVector<TVSupportedInputSourcesItem^>^ SupportedInputSources
    {
        Windows::Foundation::Collections::IVector<TVSupportedInputSourcesItem^>^ get() { return m_value; }
    internal:
        void set(_In_ Windows::Foundation::Collections::IVector<TVSupportedInputSourcesItem^>^ value) { m_value = value; }
    }

    static TVGetSupportedInputSourcesResult^ CreateSuccessResult(_In_ Windows::Foundation::Collections::IVector<TVSupportedInputSourcesItem^>^ value)
    {
        auto result = ref new TVGetSupportedInputSourcesResult();
        result->Status = Windows::Devices::AllJoyn::AllJoynStatus::Ok;
        result->SupportedInputSources = value;
        result->m_creationContext = Concurrency::task_continuation_context::use_current();
        return result;
    }

    static TVGetSupportedInputSourcesResult^ CreateFailureResult(_In_ int32 status)
    {
        auto result = ref new TVGetSupportedInputSourcesResult();
        result->Status = status;
        return result;
    }
internal:
    Concurrency::task_continuation_context m_creationContext = Concurrency::task_continuation_context::use_default();

private:
    int32 m_status;
    Windows::Foundation::Collections::IVector<TVSupportedInputSourcesItem^>^ m_value;
};

public ref class TVGetVersionResult sealed
{
public:
    property int32 Status
    {
        int32 get() { return m_status; }
    internal:
        void set(_In_ int32 value) { m_status = value; }
    }

    property uint16 Version
    {
        uint16 get() { return m_value; }
    internal:
        void set(_In_ uint16 value) { m_value = value; }
    }

    static TVGetVersionResult^ CreateSuccessResult(_In_ uint16 value)
    {
        auto result = ref new TVGetVersionResult();
        result->Status = Windows::Devices::AllJoyn::AllJoynStatus::Ok;
        result->Version = value;
        result->m_creationContext = Concurrency::task_continuation_context::use_current();
        return result;
    }

    static TVGetVersionResult^ CreateFailureResult(_In_ int32 status)
    {
        auto result = ref new TVGetVersionResult();
        result->Status = status;
        return result;
    }
internal:
    Concurrency::task_continuation_context m_creationContext = Concurrency::task_continuation_context::use_default();

private:
    int32 m_status;
    uint16 m_value;
};

} } } } 
