//-----------------------------------------------------------------------------
// <auto-generated> 
//   This code was generated by a tool. 
// 
//   Changes to this file may cause incorrect behavior and will be lost if  
//   the code is regenerated.
//
//   Tool: AllJoynCodeGenerator.exe
//
//   This tool is located in the Windows 10 SDK and the Windows 10 AllJoyn 
//   Visual Studio Extension in the Visual Studio Gallery.  
//
//   The generated code should be packaged in a Windows 10 C++/CX Runtime  
//   Component which can be consumed in any UWP-supported language using 
//   APIs that are available in Windows.Devices.AllJoyn.
//
//   Using AllJoynCodeGenerator - Invoke the following command with a valid 
//   Introspection XML file and a writable output directory:
//     AllJoynCodeGenerator -i <INPUT XML FILE> -o <OUTPUT DIRECTORY>
// </auto-generated>
//-----------------------------------------------------------------------------
#include "pch.h"

using namespace Microsoft::WRL;
using namespace Platform;
using namespace Windows::Foundation;
using namespace Windows::Foundation::Collections;
using namespace Windows::Devices::AllJoyn;
using namespace com::lg::Control::TV;

// Note: Unlike an Interface implementation, which provides a single handler for each member, the event
// model allows for 0 or more listeners to be registered. The EventAdapter implementation deals with this
// difference by implementing a last-writer-wins policy. The lack of any return value (i.e., 0 listeners)
// is handled by returning a null result.

// Methods
IAsyncOperation<TVDownChannelResult^>^ TVServiceEventAdapter::DownChannelAsync(_In_ AllJoynMessageInfo^ info)
{
    auto args = ref new TVDownChannelCalledEventArgs(info);
    DownChannelCalled(this, args);
    return TVDownChannelCalledEventArgs::GetResultAsync(args);
}

IAsyncOperation<TVGetChannelListResult^>^ TVServiceEventAdapter::GetChannelListAsync(_In_ AllJoynMessageInfo^ info, _In_ uint16 interfaceMemberStartingRecord, _In_ uint16 interfaceMemberNumRecords)
{
    auto args = ref new TVGetChannelListCalledEventArgs(info, interfaceMemberStartingRecord, interfaceMemberNumRecords);
    GetChannelListCalled(this, args);
    return TVGetChannelListCalledEventArgs::GetResultAsync(args);
}

IAsyncOperation<TVKeyInputResult^>^ TVServiceEventAdapter::KeyInputAsync(_In_ AllJoynMessageInfo^ info, _In_ uint16 interfaceMemberVirtualKeyVal)
{
    auto args = ref new TVKeyInputCalledEventArgs(info, interfaceMemberVirtualKeyVal);
    KeyInputCalled(this, args);
    return TVKeyInputCalledEventArgs::GetResultAsync(args);
}

IAsyncOperation<TVUpChannelResult^>^ TVServiceEventAdapter::UpChannelAsync(_In_ AllJoynMessageInfo^ info)
{
    auto args = ref new TVUpChannelCalledEventArgs(info);
    UpChannelCalled(this, args);
    return TVUpChannelCalledEventArgs::GetResultAsync(args);
}

// Property Reads
IAsyncOperation<TVGetChannelIDResult^>^ TVServiceEventAdapter::GetChannelIDAsync(_In_ AllJoynMessageInfo^ info)
{
    auto args = ref new TVGetChannelIDRequestedEventArgs(info);
    GetChannelIDRequested(this, args);
    return TVGetChannelIDRequestedEventArgs::GetResultAsync(args);
}

IAsyncOperation<TVGetInputSourceResult^>^ TVServiceEventAdapter::GetInputSourceAsync(_In_ AllJoynMessageInfo^ info)
{
    auto args = ref new TVGetInputSourceRequestedEventArgs(info);
    GetInputSourceRequested(this, args);
    return TVGetInputSourceRequestedEventArgs::GetResultAsync(args);
}

IAsyncOperation<TVGetSupportedInputSourcesResult^>^ TVServiceEventAdapter::GetSupportedInputSourcesAsync(_In_ AllJoynMessageInfo^ info)
{
    auto args = ref new TVGetSupportedInputSourcesRequestedEventArgs(info);
    GetSupportedInputSourcesRequested(this, args);
    return TVGetSupportedInputSourcesRequestedEventArgs::GetResultAsync(args);
}

IAsyncOperation<TVGetVersionResult^>^ TVServiceEventAdapter::GetVersionAsync(_In_ AllJoynMessageInfo^ info)
{
    auto args = ref new TVGetVersionRequestedEventArgs(info);
    GetVersionRequested(this, args);
    return TVGetVersionRequestedEventArgs::GetResultAsync(args);
}

// Property Writes
IAsyncOperation<TVSetChannelIDResult^>^ TVServiceEventAdapter::SetChannelIDAsync(_In_ AllJoynMessageInfo^ info, _In_ Platform::String^ value)
{
    auto args = ref new TVSetChannelIDRequestedEventArgs(info, value);
    SetChannelIDRequested(this, args);
    return TVSetChannelIDRequestedEventArgs::GetResultAsync(args);
}

IAsyncOperation<TVSetInputSourceResult^>^ TVServiceEventAdapter::SetInputSourceAsync(_In_ AllJoynMessageInfo^ info, _In_ uint16 value)
{
    auto args = ref new TVSetInputSourceRequestedEventArgs(info, value);
    SetInputSourceRequested(this, args);
    return TVSetInputSourceRequestedEventArgs::GetResultAsync(args);
}

