//-----------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//   Changes to this file may cause incorrect behavior and will be lost if
//   the code is regenerated.
//
//   For more information, see: http://go.microsoft.com/fwlink/?LinkID=623246
// </auto-generated>
//-----------------------------------------------------------------------------
#include "pch.h"

using namespace Microsoft::WRL;
using namespace Platform;
using namespace Windows::Devices::AllJoyn;
using namespace Windows::Foundation;
using namespace com::lg::Control::TV;

void TVSignals::Initialize(_In_ alljoyn_busobject busObject, _In_ alljoyn_sessionid sessionId)
{
    m_busObject = busObject;
    m_sessionId = sessionId;

    auto interfaceDefinition = alljoyn_busattachment_getinterface(alljoyn_busobject_getbusattachment(busObject), "com.lg.Control.TV");
    alljoyn_interfacedescription_getmember(interfaceDefinition, "ChannelListChanged", &m_memberChannelListChanged);
    alljoyn_interfacedescription_getmember(interfaceDefinition, "ChannelNumberChanged", &m_memberChannelNumberChanged);
    alljoyn_interfacedescription_getmember(interfaceDefinition, "InputSourceChanged", &m_memberInputSourceChanged);
}

void TVSignals::ChannelListChanged()
{
    if (nullptr == m_busObject)
    {
        return;
    }

    size_t argCount = 0;
    alljoyn_msgarg arguments = alljoyn_msgarg_array_create(argCount);
    
    alljoyn_busobject_signal(
        m_busObject, 
        NULL,  // Generated code only supports broadcast signals.
        m_sessionId,
        m_memberChannelListChanged,
        arguments,
        argCount, 
        0, // A signal with a TTL of 0 will be sent to every member of the session, regardless of how long it takes to deliver the message
        ALLJOYN_MESSAGE_FLAG_GLOBAL_BROADCAST, // Broadcast to everyone in the session.
        NULL); // The generated code does not need the generated signal message

    alljoyn_msgarg_destroy(arguments);
}

void TVSignals::CallChannelListChangedReceived(_In_ TVSignals^ sender, _In_ TVChannelListChangedReceivedEventArgs^ args)
{
    ChannelListChangedReceived(sender, args);
}

void TVSignals::ChannelNumberChanged(_In_ TVChannelDescriptor^ interfaceMemberChannelDescriptor)
{
    if (nullptr == m_busObject)
    {
        return;
    }

    size_t argCount = 1;
    alljoyn_msgarg arguments = alljoyn_msgarg_array_create(argCount);
    (void)TypeConversionHelpers::SetAllJoynMessageArg(alljoyn_msgarg_array_element(arguments, 0), "(sqss)", interfaceMemberChannelDescriptor);
    
    alljoyn_busobject_signal(
        m_busObject, 
        NULL,  // Generated code only supports broadcast signals.
        m_sessionId,
        m_memberChannelNumberChanged,
        arguments,
        argCount, 
        0, // A signal with a TTL of 0 will be sent to every member of the session, regardless of how long it takes to deliver the message
        ALLJOYN_MESSAGE_FLAG_GLOBAL_BROADCAST, // Broadcast to everyone in the session.
        NULL); // The generated code does not need the generated signal message

    alljoyn_msgarg_destroy(arguments);
}

void TVSignals::CallChannelNumberChangedReceived(_In_ TVSignals^ sender, _In_ TVChannelNumberChangedReceivedEventArgs^ args)
{
    ChannelNumberChangedReceived(sender, args);
}

void TVSignals::InputSourceChanged(_In_ uint16 interfaceMemberNewInputSource)
{
    if (nullptr == m_busObject)
    {
        return;
    }

    size_t argCount = 1;
    alljoyn_msgarg arguments = alljoyn_msgarg_array_create(argCount);
    (void)TypeConversionHelpers::SetAllJoynMessageArg(alljoyn_msgarg_array_element(arguments, 0), "q", interfaceMemberNewInputSource);
    
    alljoyn_busobject_signal(
        m_busObject, 
        NULL,  // Generated code only supports broadcast signals.
        m_sessionId,
        m_memberInputSourceChanged,
        arguments,
        argCount, 
        0, // A signal with a TTL of 0 will be sent to every member of the session, regardless of how long it takes to deliver the message
        ALLJOYN_MESSAGE_FLAG_GLOBAL_BROADCAST, // Broadcast to everyone in the session.
        NULL); // The generated code does not need the generated signal message

    alljoyn_msgarg_destroy(arguments);
}

void TVSignals::CallInputSourceChangedReceived(_In_ TVSignals^ sender, _In_ TVInputSourceChangedReceivedEventArgs^ args)
{
    InputSourceChangedReceived(sender, args);
}

