//-----------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//   Changes to this file may cause incorrect behavior and will be lost if
//   the code is regenerated.
//
//   For more information, see: http://go.microsoft.com/fwlink/?LinkID=623246
// </auto-generated>
//-----------------------------------------------------------------------------
#pragma once

namespace com { namespace lg { namespace Control { namespace TV {

public ref class TVListOfChannelsItem sealed
{
public:
    property Platform::String^ Value1
    {
        Platform::String^ get() { return m_value1; }
        void set(Platform::String^ value) { m_value1 = value; }
    }
     
    property uint16 Value2
    {
        uint16 get() { return m_value2; }
        void set(uint16 value) { m_value2 = value; }
    }
     
    property Platform::String^ Value3
    {
        Platform::String^ get() { return m_value3; }
        void set(Platform::String^ value) { m_value3 = value; }
    }
     
    property Platform::String^ Value4
    {
        Platform::String^ get() { return m_value4; }
        void set(Platform::String^ value) { m_value4 = value; }
    }
     
private:
    Platform::String^ m_value1;
    uint16 m_value2;
    Platform::String^ m_value3;
    Platform::String^ m_value4;
};

public ref class TVChannelDescriptor sealed
{
public:
    property Platform::String^ Value1
    {
        Platform::String^ get() { return m_value1; }
        void set(Platform::String^ value) { m_value1 = value; }
    }
     
    property uint16 Value2
    {
        uint16 get() { return m_value2; }
        void set(uint16 value) { m_value2 = value; }
    }
     
    property Platform::String^ Value3
    {
        Platform::String^ get() { return m_value3; }
        void set(Platform::String^ value) { m_value3 = value; }
    }
     
    property Platform::String^ Value4
    {
        Platform::String^ get() { return m_value4; }
        void set(Platform::String^ value) { m_value4 = value; }
    }
     
private:
    Platform::String^ m_value1;
    uint16 m_value2;
    Platform::String^ m_value3;
    Platform::String^ m_value4;
};

public ref class TVSupportedInputSourcesItem sealed
{
public:
    property uint16 Value1
    {
        uint16 get() { return m_value1; }
        void set(uint16 value) { m_value1 = value; }
    }
     
    property Platform::String^ Value2
    {
        Platform::String^ get() { return m_value2; }
        void set(Platform::String^ value) { m_value2 = value; }
    }
     
    property Platform::String^ Value3
    {
        Platform::String^ get() { return m_value3; }
        void set(Platform::String^ value) { m_value3 = value; }
    }
     
private:
    uint16 m_value1;
    Platform::String^ m_value2;
    Platform::String^ m_value3;
};

public ref class AllJoynMessageArgStructure sealed : Windows::Foundation::Collections::IVector<Platform::Object^>
{
public:
    AllJoynMessageArgStructure()
    {
        m_vector = ref new Platform::Collections::Vector<Platform::Object^>();
    }

    virtual Windows::Foundation::Collections::IIterator<Platform::Object^>^ First()
    {
        return m_vector->First();
    }

    virtual Platform::Object^ GetAt(unsigned int index)
    {
        return m_vector->GetAt(index);
    }

    virtual property unsigned int Size {
        virtual unsigned int get()
        {
            return m_vector->Size;
        }
    }

    virtual bool IndexOf(Platform::Object^ value, unsigned int * index)
    {
        return m_vector->IndexOf(value, index);
    }

    virtual unsigned int GetMany(unsigned int startIndex, Platform::WriteOnlyArray<Platform::Object^>^ items)
    {
        return m_vector->GetMany(startIndex, items);
    }

    virtual Windows::Foundation::Collections::IVectorView<Platform::Object^>^ GetView()
    {
        return m_vector->GetView();
    }

    virtual void SetAt(unsigned int index, Platform::Object^ value)
    {
        return m_vector->SetAt(index, value);
    }

    virtual void InsertAt(unsigned int index, Platform::Object^ value)
    {
        return m_vector->InsertAt(index, value);
    }

    virtual void Append(Platform::Object^ value)
    {
        return m_vector->Append(value);
    }

    virtual void RemoveAt(unsigned int index)
    {
        return m_vector->RemoveAt(index);
    }

    virtual void RemoveAtEnd()
    {
        return m_vector->RemoveAtEnd();
    }

    virtual void Clear()
    {
        return m_vector->Clear();
    }

    virtual void ReplaceAll(const Platform::Array<Platform::Object^>^ items)
    {
        return m_vector->ReplaceAll(items);
    }

private:
    Platform::Collections::Vector<Platform::Object^>^ m_vector;
};
} } } } 

partial ref class TypeConversionHelpers
{
internal:
    static _Check_return_ int32 GetAllJoynMessageArg(_In_ alljoyn_msgarg argument, _In_ PCSTR signature, _Out_ com::lg::Control::TV::TVListOfChannelsItem^* value)
    {
        UNREFERENCED_PARAMETER(signature);

        (*value) = ref new com::lg::Control::TV::TVListOfChannelsItem();

        alljoyn_msgarg argument1;
        alljoyn_msgarg argument2;
        alljoyn_msgarg argument3;
        alljoyn_msgarg argument4;
        RETURN_IF_QSTATUS_ERROR(alljoyn_msgarg_get(argument, "(****)", &argument1, &argument2, &argument3, &argument4));

        Platform::String^ value1;
        RETURN_IF_QSTATUS_ERROR(GetAllJoynMessageArg(argument1, "s", &value1));
        (*value)->Value1 = value1;
        uint16 value2;
        RETURN_IF_QSTATUS_ERROR(GetAllJoynMessageArg(argument2, "q", &value2));
        (*value)->Value2 = value2;
        Platform::String^ value3;
        RETURN_IF_QSTATUS_ERROR(GetAllJoynMessageArg(argument3, "s", &value3));
        (*value)->Value3 = value3;
        Platform::String^ value4;
        RETURN_IF_QSTATUS_ERROR(GetAllJoynMessageArg(argument4, "s", &value4));
        (*value)->Value4 = value4;
        
        return ER_OK;
    }

    static _Check_return_ int32 SetAllJoynMessageArg(_In_ alljoyn_msgarg argument, _In_ PCSTR signature, _In_ com::lg::Control::TV::TVListOfChannelsItem^ value)
    {
        UNREFERENCED_PARAMETER(signature);

        auto argument1 = alljoyn_msgarg_create();
        RETURN_IF_QSTATUS_ERROR(SetAllJoynMessageArg(argument1, "s", value->Value1));
        auto argument2 = alljoyn_msgarg_create();
        RETURN_IF_QSTATUS_ERROR(SetAllJoynMessageArg(argument2, "q", value->Value2));
        auto argument3 = alljoyn_msgarg_create();
        RETURN_IF_QSTATUS_ERROR(SetAllJoynMessageArg(argument3, "s", value->Value3));
        auto argument4 = alljoyn_msgarg_create();
        RETURN_IF_QSTATUS_ERROR(SetAllJoynMessageArg(argument4, "s", value->Value4));

        RETURN_IF_QSTATUS_ERROR(alljoyn_msgarg_set(argument, "(****)", argument1, argument2, argument3, argument4));
        alljoyn_msgarg_stabilize(argument);
        alljoyn_msgarg_destroy(argument1);
        alljoyn_msgarg_destroy(argument2);
        alljoyn_msgarg_destroy(argument3);
        alljoyn_msgarg_destroy(argument4);

        return ER_OK;
    }

    static _Check_return_ int32 GetAllJoynMessageArg(_In_ alljoyn_msgarg argument, _In_ PCSTR signature, _Out_ com::lg::Control::TV::TVChannelDescriptor^* value)
    {
        UNREFERENCED_PARAMETER(signature);

        (*value) = ref new com::lg::Control::TV::TVChannelDescriptor();

        alljoyn_msgarg argument1;
        alljoyn_msgarg argument2;
        alljoyn_msgarg argument3;
        alljoyn_msgarg argument4;
        RETURN_IF_QSTATUS_ERROR(alljoyn_msgarg_get(argument, "(****)", &argument1, &argument2, &argument3, &argument4));

        Platform::String^ value1;
        RETURN_IF_QSTATUS_ERROR(GetAllJoynMessageArg(argument1, "s", &value1));
        (*value)->Value1 = value1;
        uint16 value2;
        RETURN_IF_QSTATUS_ERROR(GetAllJoynMessageArg(argument2, "q", &value2));
        (*value)->Value2 = value2;
        Platform::String^ value3;
        RETURN_IF_QSTATUS_ERROR(GetAllJoynMessageArg(argument3, "s", &value3));
        (*value)->Value3 = value3;
        Platform::String^ value4;
        RETURN_IF_QSTATUS_ERROR(GetAllJoynMessageArg(argument4, "s", &value4));
        (*value)->Value4 = value4;
        
        return ER_OK;
    }

    static _Check_return_ int32 SetAllJoynMessageArg(_In_ alljoyn_msgarg argument, _In_ PCSTR signature, _In_ com::lg::Control::TV::TVChannelDescriptor^ value)
    {
        UNREFERENCED_PARAMETER(signature);

        auto argument1 = alljoyn_msgarg_create();
        RETURN_IF_QSTATUS_ERROR(SetAllJoynMessageArg(argument1, "s", value->Value1));
        auto argument2 = alljoyn_msgarg_create();
        RETURN_IF_QSTATUS_ERROR(SetAllJoynMessageArg(argument2, "q", value->Value2));
        auto argument3 = alljoyn_msgarg_create();
        RETURN_IF_QSTATUS_ERROR(SetAllJoynMessageArg(argument3, "s", value->Value3));
        auto argument4 = alljoyn_msgarg_create();
        RETURN_IF_QSTATUS_ERROR(SetAllJoynMessageArg(argument4, "s", value->Value4));

        RETURN_IF_QSTATUS_ERROR(alljoyn_msgarg_set(argument, "(****)", argument1, argument2, argument3, argument4));
        alljoyn_msgarg_stabilize(argument);
        alljoyn_msgarg_destroy(argument1);
        alljoyn_msgarg_destroy(argument2);
        alljoyn_msgarg_destroy(argument3);
        alljoyn_msgarg_destroy(argument4);

        return ER_OK;
    }

    static _Check_return_ int32 GetAllJoynMessageArg(_In_ alljoyn_msgarg argument, _In_ PCSTR signature, _Out_ com::lg::Control::TV::TVSupportedInputSourcesItem^* value)
    {
        UNREFERENCED_PARAMETER(signature);

        (*value) = ref new com::lg::Control::TV::TVSupportedInputSourcesItem();

        alljoyn_msgarg argument1;
        alljoyn_msgarg argument2;
        alljoyn_msgarg argument3;
        RETURN_IF_QSTATUS_ERROR(alljoyn_msgarg_get(argument, "(***)", &argument1, &argument2, &argument3));

        uint16 value1;
        RETURN_IF_QSTATUS_ERROR(GetAllJoynMessageArg(argument1, "q", &value1));
        (*value)->Value1 = value1;
        Platform::String^ value2;
        RETURN_IF_QSTATUS_ERROR(GetAllJoynMessageArg(argument2, "s", &value2));
        (*value)->Value2 = value2;
        Platform::String^ value3;
        RETURN_IF_QSTATUS_ERROR(GetAllJoynMessageArg(argument3, "s", &value3));
        (*value)->Value3 = value3;
        
        return ER_OK;
    }

    static _Check_return_ int32 SetAllJoynMessageArg(_In_ alljoyn_msgarg argument, _In_ PCSTR signature, _In_ com::lg::Control::TV::TVSupportedInputSourcesItem^ value)
    {
        UNREFERENCED_PARAMETER(signature);

        auto argument1 = alljoyn_msgarg_create();
        RETURN_IF_QSTATUS_ERROR(SetAllJoynMessageArg(argument1, "q", value->Value1));
        auto argument2 = alljoyn_msgarg_create();
        RETURN_IF_QSTATUS_ERROR(SetAllJoynMessageArg(argument2, "s", value->Value2));
        auto argument3 = alljoyn_msgarg_create();
        RETURN_IF_QSTATUS_ERROR(SetAllJoynMessageArg(argument3, "s", value->Value3));

        RETURN_IF_QSTATUS_ERROR(alljoyn_msgarg_set(argument, "(***)", argument1, argument2, argument3));
        alljoyn_msgarg_stabilize(argument);
        alljoyn_msgarg_destroy(argument1);
        alljoyn_msgarg_destroy(argument2);
        alljoyn_msgarg_destroy(argument3);

        return ER_OK;
    }

};
